---
# @see https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
# @see https://docs.github.com/en/actions/guides/creating-postgresql-service-containers
# @see https://github.com/actions/virtual-environments
# @see https://www.postgresql.jp/document/11/html/app-pgrestore.html
name: Test
on:
  push:
    branches:
      - "**"
jobs:
  test:
    name: Test
    timeout-minutes: 3
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_INITDB_ARGS: '--auth-host=scram-sha-256'
    env:
      PGHOST: 127.0.0.1
      PGPORT: 5432
      PGDATABASE: postgres
    steps:
      - name: Install PostgreSQL clients
        run: sudo apt update && sudo apt install -y --no-install-recommends postgresql-client

      - name: Check out code
        uses: actions/checkout@v2

      - name: Build
        run: make

      - name: Create role for test
        run: |
          echo -n "CREATE ROLE $PGUSER WITH LOGIN PASSWORD " >> $SQL_FILE_PATH
          echo -n "'"                                        >> $SQL_FILE_PATH
          ./encrypt $PGPASSWORD | tr -d '\n'                 >> $SQL_FILE_PATH
          echo "';"                                          >> $SQL_FILE_PATH
          cat $SQL_FILE_PATH
          cat $SQL_FILE_PATH | psql
        env:
          SQL_FILE_PATH: /tmp/create_role.sql
          PGUSER: postgres
          PGPASSWORD: postgres

      - name: Check roles out
        run: psql -c 'SELECT usename, passwd FROM pg_catalog.pg_shadow'
        env:
          PGUSER: postgres
          PGPASSWORD: postgres

      - name: Test login success
        run: psql -c 'SELECT user'
        env:
          PGUSER: test
          PGPASSWORD: test

      - name: Test login fail
        run: psql -c 'SELECT user' || echo 'fail ok'
        env:
          PGUSER: test
          PGPASSWORD: wrong
